# Generated by Django 5.1.1 on 2024-10-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('pres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('square', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bathroom', models.IntegerField()),
                ('room', models.IntegerField()),
                ('garage', models.BooleanField(default=False)),
            ],
        ),
    ]
