# Generated by Django 5.1.1 on 2024-10-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_pres_details_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='typePrice',
            field=models.CharField(choices=[('شراء', 'شراء'), ('ايجار', 'ايجار')], default='شراء', max_length=10),
        ),
    ]
