# Generated by Django 5.1.1 on 2024-10-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_details_typeprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='description',
            field=models.CharField(default='لا يوجد وصف', max_length=20),
        ),
    ]
