# Generated by Django 5.1.1 on 2024-10-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_details_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='description',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='details',
            name='typePrice',
            field=models.CharField(choices=[('شراء', 'شراء'), ('ايجار', 'ايجار')], default='', max_length=10),
        ),
    ]
