# Generated by Django 5.1.1 on 2024-10-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_details_description_alter_details_typeprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
