# Generated by Django 5.1.1 on 2024-10-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_details_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='description',
            field=models.CharField(default='', max_length=150),
        ),
    ]
