# Generated by Django 5.1.1 on 2024-10-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_details_image_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
