# Generated by Django 5.1.1 on 2024-10-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_details_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='image',
            field=models.JSONField(default=list),
        ),
    ]
