# Generated by Django 5.1.1 on 2024-10-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_details_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='image',
        ),
        migrations.AddField(
            model_name='details',
            name='images',
            field=models.TextField(blank=True),
        ),
    ]
