# Generated by Django 5.1.1 on 2024-10-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_details_image_details_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='images',
            field=models.TextField(blank=True, null=True),
        ),
    ]
