# Generated by Django 5.1.1 on 2024-10-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_details_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='images',
        ),
        migrations.AddField(
            model_name='details',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
