# Generated by Django 5.1.1 on 2024-10-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_details_image_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
