# Generated by Django 5.1.1 on 2024-11-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='typePrice',
        ),
        migrations.AddField(
            model_name='details',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
