# Generated by Django 5.1.1 on 2024-11-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_details_typeprice_details_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='typePrice',
            field=models.CharField(choices=[('شراء', 'شراء'), ('ايجار', 'ايجار')], default='', max_length=10),
        ),
    ]
