# Generated by Django 5.1.1 on 2025-01-10 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_details_typeprice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='House',
        ),
    ]
