# Generated by Django 5.1.1 on 2025-01-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_details_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('typePrice', models.CharField(choices=[('شراء', 'شراء'), ('ايجار', 'ايجار')], default='', max_length=10)),
                ('favorite', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=255)),
                ('square', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bathroom', models.IntegerField()),
                ('room', models.IntegerField()),
                ('garage', models.BooleanField(default=False)),
                ('description', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Featuredproperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('typePrice', models.CharField(choices=[('شراء', 'شراء'), ('ايجار', 'ايجار')], default='', max_length=10)),
                ('favorite', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=255)),
                ('square', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bathroom', models.IntegerField()),
                ('room', models.IntegerField()),
                ('garage', models.BooleanField(default=False)),
                ('description', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Plotsofland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('typePrice', models.CharField(choices=[('شراء', 'شراء')], default='', max_length=10)),
                ('favorite', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=255)),
                ('square', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bathroom', models.IntegerField()),
                ('room', models.IntegerField()),
                ('garage', models.BooleanField(default=False)),
                ('description', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
